version: '3.1'
volumes:
  data:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${DOCKER_MYSQL_DATABASE}"
      MYSQL_USER: "${DOCKER_MYSQL_USER}"
      MYSQL_PASSWORD: "${DOCKER_MYSQL_PASSWORD}"
    volumes:
      - data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
